
server:
    port: 8888
    servlet:
        context-path: /api/fantastic
spring:
    application:
        name: fantastic

    datasource:
        url: jdbc:mysql://localhost:3306/fan?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
        username: root
        password: root
        driver-class-name: com.mysql.cj.jdbc.Driver
        type: com.zaxxer.hikari.HikariDataSource
        